# Site settings
title: Strong Horse Consulting
email: tehmasp@chaudhri.me
url: https://stronghorseconsulting.com
description: "IT consulting specializing in Cloud Computing, Dev/Ops, Linux system administration, and Google G Suite."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Strong Horse Consulting

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/stronghorsellc
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
